version: 2

updates:
- package-ecosystem: "gomod"
  directory: "/app"
  schedule:
    interval: "daily" 
#- package-ecosystem: "docker"
#  open-pull-requests-limit: 10
#  directory: "/"
#  schedule:
#    interval: "daily" 
- package-ecosystem: "docker"
  open-pull-requests-limit: 10
  directory: "/app"
  schedule:
    interval: "daily" 
- package-ecosystem: "github-actions"
  directory: /
  schedule:
    interval: "daily"
