version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /app
    schedule:
      interval: monthly
  - package-ecosystem: gomod
    open-pull-requests-limit: 10
    directory: /app
    schedule:
      interval: weekly
