version: 2

updates:
- package-ecosystem: "gomod"
  directory: "/app"
  schedule:
    interval: "daily" 
- package-ecosystem: "docker"
  defaults:
  run:
    working-directory: app
  #open-pull-requests-limit: 10
  #directory: "/app"
  directory: "/"
  schedule:
    interval: "daily" 
- package-ecosystem: "github-actions"
  directory: /
  schedule:
    interval: "daily"
