version: 2
updates:
- package-ecosystem: "gomod"
  directory: "/app"
  schedule:
    interval: "daily" 
  #target-branch: "component-updates" 
- package-ecosystem: "docker"
  open-pull-requests-limit: 10
  directory: "/app/Dockerfile"
  schedule:
    interval: "daily" 
  #target-branch: "component-updates" 
- package-ecosystem: "docker"
  open-pull-requests-limit: 10
  directory: "/app/Dockerfile.distroless"
  schedule:
    interval: "daily" 
- package-ecosystem: "docker"
  open-pull-requests-limit: 10
  directory: "/app/Dockerfile.ubuntugo"
  schedule:
    interval: "daily" 
  #target-branch: "component-updates"
- package-ecosystem: "github-actions"
  directory: /
  schedule:
    interval: "daily"
