version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        #variable: a_value
        GITHUB_TOKEN: "yertoken"
        KEYCHAIN_APP_SERVICE: "github-forkrefresh"
        KEYCHAIN_USERNAME: "dmore"