version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        #variable: a_value
        GITHUB_TOKEN: "yertoken"
        KEYCHAIN_APP_SERVICE: "github-forkrefresh"
        KEYCHAIN_USERNAME: "dmore"
        REPOS_GIST: "https://gist.githubusercontent.com/dmore/5c26c5c2484aa13736f22d80e8bf4e7e/raw/88ebe3b0d641fc7e8715bfe4056625ac2532953b/repos_repo.json"