name: 'Build'

on: [push]

jobs:
  run-tests:
    #if: ${{ github.actor != 'dependabot[bot]' }}
    name: Build Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          KEYCHAIN_APP_SERVICE: ${{ secrets.KEYCHAIN_APP_SERVICE }}
          KEYCHAIN_USERNAME: ${{ secrets.KEYCHAIN_USERNAME }}
        with:
          image: dmore/forkrefresh
          tags: v1, latest
          #use default
          #registry: registry-url.io
          registry: index.docker.io/v1/
          #registry: https://index.docker.io/v2/ 
          dockerfile: app/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
