name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      GO111MODULE: "on"
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      KEYCHAIN_APP_SERVICE: ${{ secrets.KEYCHAIN_APP_SERVICE }}
      KEYCHAIN_USERNAME: ${{ secrets.KEYCHAIN_USERNAME }}
      REPOS_GIST: ${{ secrets.REPOS_GIST }}
    defaults:
      run:
        working-directory: app
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag forkrefresh:$(date +%s)

  run:
    
    runs-on: ubuntu-latest
    env:
      GO111MODULE: "on"
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      KEYCHAIN_APP_SERVICE: ${{ secrets.KEYCHAIN_APP_SERVICE }}
      KEYCHAIN_USERNAME: ${{ secrets.KEYCHAIN_USERNAME }}
      REPOS_GIST: ${{ secrets.REPOS_GIST }}
    defaults:
      run:
        working-directory: app
    steps:
    - name: Checkout 
      uses: actions/checkout@v2 # Required to mount the Github Workspace to a volume 
    - uses: addnab/docker-run-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: docker.io
        #image: private-image:latest
        image: dmore/github-forkrefresh-docker:main
        #options: -v ${{ github.workspace }}:/app -e ABC=123
        options: -v ${{ github.workspace }}:/app -e REPOS_GIST=${{ secrets.REPOS_GIST }}
        run: |
          /app