name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      GO111MODULE: "on"
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      KEYCHAIN_APP_SERVICE: ${{ secrets.KEYCHAIN_APP_SERVICE }}
      KEYCHAIN_USERNAME: ${{ secrets.KEYCHAIN_USERNAME }}
    defaults:
      run:
        working-directory: app
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag forkrefresh:$(date +%s)

      #docker: Error response from daemon: pull access denied for forkrefresh, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
      #docker run -d -t -i --name githubforkrefresh docker.io/library/forkrefresh:1695492549
  #  - uses: actions/checkout@v3
  #  - name: Run the Docker image
  #    run: docker run -d -t -i --name githubforkrefresh docker.io/library/forkrefresh
