name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    #runs-on: ubuntu-latest
    #runs-on: ubuntu-18.04
    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag forkrefresh:$(date +%s)